Feature/43 implement the threat notification
MSU-CS4360-WhiteHat/ecommerce-scam-detector pull request #50
Opened 2023-02-28 18:00 UTC by LucasMali

- [x] It has the logic to allow the payload to be modified. 
- [x] It will render when called showing the payload.

2023-02-28 19:19 UTC, thrandale requested changes

2023-02-28 19:19 UTC, thrandale commented on src/background/background.js
> +"use strict";
This is breaking the other stuff. With it in, the api request never gets sent. I am not sure why.
Is this required?

2023-03-01 14:46 UTC, LucasMali commented on src/background/background.js
> +"use strict";
@thrandale I can take a look at the other stuff. Is it needed, mostly yes, little bit no. _Use Strict_ is industry standard. It helps with more strict type casting, more explicit error messages, and security. I can spend some time during lunch to review the code and behavior--maybe a callback or something isn't working as expected and needs to be converted to a promise. 

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
- https://love2dev.com/blog/javascript-strict-mode/
- https://stackoverflow.com/questions/42295368/use-promises-instead-of-callbacks

cc: @corywilson88

2023-03-02 22:45 UTC, thrandale approved these changes

2023-03-04 00:09 UTC, LucasMali commented
@corywilson88 Are you good with this feature?

2023-03-04 13:32 UTC, merged